### PR TITLE
Boot upgrade command

### PR DESCRIPTION
**Pull request by fabapp2**
Adds command `boot upgrade <path>` to `BootCommands`.
The command executes the OpenRewrite recipe `org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1` and writes the changes to the provided `<path>`.
`spring-rewrite-commons` provides a new `spring-rewrite-commons-starter-boot-upgrade` which provides the required components and recipes jars,

- [x] How do we test this, it takes minutes to run? IMHO it should be tested in `spring-rewrite-commons` ? 
- [x] And `spring-cli` should "just" do a unittest (?)
- [x] The new `RewriteRecipeRunner` should rather be a component in `spring-rewrite-commons` (?)

### CODE REVIEW

**Comment by markpollack** [comment]
I think there are some `System.out.println` that should be removed.  Here is a sample output.


```
$ spring boot upgrade --help
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
Helper 'slugify' has been replaced by 'slugify'
Helper 'capitalize' has been replaced by 'capitalize'
Helper 'wordWrap' has been replaced by 'wordWrap'
NAME
       boot upgrade - Apply a set of automated migrations to upgrade a Boot application.

SYNOPSIS
       boot upgrade --path String --help 

OPTIONS
       --path String
       Path
       [Optional]

       --help or -h 
       help for boot upgrade
       [Optional]


```

**Comment by markpollack** [comment]
Ran these commands in spring cli and the upgrade failed as shown below.

```
spring boot new myapp --package-name com.xkcd.demo

spring boot add jpa

spring ai add "Generated using the description: JPA functionality with an integration test.  Include all Java code in the same package. Use ObjectMapper to serialize a Java object to a JSON String in integration tests" --preview 

spring guide apply README-ai-boot.md
```

The output to `spring boot upgrade` is

```
Helper 'wordWrap' has been replaced by 'wordWrap'
Start parsing dir '/tmp/testing/myapp'
java.lang.RuntimeException: org.openrewrite.java.JavaParsingException: Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /tmp/testing/myapp/.spring/commands/controller/new/RestController.java)
--- END PATH ---


Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
Application run failed
org.springframework.shell.boot.ExitCodeAutoConfiguration$ShellExitCodeException: null
	at org.springframework.shell.boot.ExitCodeAutoConfiguration.lambda$exitCodeExceptionProvider$0(ExitCodeAutoConfiguration.java:55)
	at org.springframework.shell.Shell.run(Shell.java:179)
	at org.springframework.shell.jline.NonInteractiveShellRunner.run(NonInteractiveShellRunner.java:146
```

No files were changed in the directory.

**Comment by fabapp2** [comment]
@markpollack could you do me a favour and paste the zipped result that triggered the error here?
The parser failed. Could the application that was generated have some issues? 
Did you maybe try (or know) if it runs?

**Comment by fabapp2** [comment]
I fiddled with the logger configuration to have some output for now.
We need to decide how we deal with long-running commands. 
Is there some component to print to console?

**Comment by markpollack** [comment]
[myapp.zip](https://github.com/spring-projects/spring-cli/files/14027934/myapp.zip)

**Comment by markpollack** [comment]
i think for now, long running command just run long.  We can put an estimate of how long we think it might take, I do that for the `spring ai add` command.

There is a class named `TerminalMessage` that lets you write to the terminal.  Here is some sample usage you can find in `ProjectHandler.java`


```
		AttributedStringBuilder sb = new AttributedStringBuilder();
		sb.style(sb.style().foreground(AttributedStyle.GREEN));
		sb.append("Getting ");
		sb.style(sb.style().foreground(AttributedStyle.WHITE));
		sb.append("project from " + urlToUse);
		terminalMessage.print(sb.toAttributedString());
```

**Comment by markpollack** [comment]
Woo hoo!  :partying_face:   Merged in 7c5cd701726e0e75a3b1e437709da7534ca70192

**Pull request closed without merging**
